---
title: "Logistic Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Upload data 
```{r}
TCC <- read.csv(file = "C:/users/arifr/Downloads/TCC.csv", header = T, stringsAsFactors = T)
```

```{r}
#change (y) to as.factor
TCC$default <- as.factor(TCC$default)
#change (x) variables to factors 
cols <-c(2:4, 6:11)
TCC[cols] <-lapply(TCC[cols], factor)
str(TCC)
summary(TCC)
```
#Entropy 
```{r}
#Calculate entropy 
Entropy <- information_gain(default~., data = TCC)
#Sort entropy distribution in order
attributes <- Entropy[order(Entropy$importance),]
#Keep 9 (X) variables with highest entropy -> reducing 24 variables to 10 in newdataset 
new_dataset <- TCC[c(12:20,24)]
```
#Split dataset into Train(70%) and Test(30%)
```{r}
#Data is split into Train(21040 obs) and Test (8960 obs)
set.seed(123)
split_data <- sample(2, nrow(new_dataset), replace = TRUE, prob = c(0.7, 0.3))
train <- new_dataset[split_data==1,]
test <- new_dataset[split_data==2,]
```
#Create Model using Training data 
```{r}
library(broom)
library(tidyverse)
library(modelr)
model <- glm(default ~., family=binomial(link='logit'), data=train)
summary(model)
anova(model, test = "Chisq")
tidy(model)
exp(coef(model))
caret::varImp(model)
#Variables that have high influence on the (Y) variables such as PAY_AMT1 (9.5), PAY_AMT2(9.0), BILL_AMT1(6.8),PAY_AMT3(5.4). 
```
#Predictive accuracy of Model using Testing data 
```{r}
#using Testing data and only X variables 
test_forest <- predict(model,newdata=subset(test, select=c(1,2,3,4,5,6,7,8,9)),type='response')
#setting parameters > 0.5 then yes y=1
test_forest <- ifelse(test_forest > 0.5,1,0)
#error (using test dataset and Y variable)
misClasificError <- mean(test_forest != test$default)
#Accuracy 
print(paste('Accuracy',1-misClasificError))
#Accuracy is 0.78
```
#ROC and AUC are performance measures for binary classifers
#ROC is plotting TRR vs FPR at different threshold 
#AUC should be closer to 1 then 0.5
#ROC <- Test data
```{r}
library(ROCR)
#Using Testing data and X variables 
p <- predict(model,newdata=subset(test,select=c(1,2,3,4,5,6,7,8,9)),type='response')
#Testing data and Y variable 
pr <- prediction(p, test$default)

#Performance of TP and FP
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
#plot 
plot(prf, main = "Logistic Regression", col=2, lwd=2)
abline(a=0, b=1, lwd=2, lty=2, col="gray")
#AUC
auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
#auc is 0.66
```

```{r}

```

```{r}

```
