---
title: "Random Forest TCC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Random Forest 
```{r}
#load dataset
TCC <- read.csv(file = "C:/users/arifr/Downloads/TCC.csv", header=TRUE)
str(TCC)
```
#Data cleaning 
```{r}
#change (Y) dependent variable to factor
TCC$default <- as.factor(TCC$default)
#chage (X) variables to factor
cols <-c(2:4, 6:11)
TCC[cols] <-lapply(TCC[cols], factor)
str(TCC)
summary(TCC)
```
#Entropy 
```{r}
library(FSelectorRcpp)
#Calculate Entropy to reduce # of attributes 
Entropy <- information_gain(default~., data = TCC)
#sort entropy in order
attributes <- Entropy[order(Entropy$importance),]
#Keep 9 (X) variables with highest entropy -> reducing 24 variables to 10 in newdataset
new_dataset <- TCC[c(12:20,24)]
```
#Cross Validation using trainin data
```{r}
library(caTools)
library(caret)
#Split dataset
ind <- createDataPartition(new_dataset$default, p= 0.7, list = FALSE)
train_cv <- new_dataset[ind,]
test_cv <- new_dataset[-ind,]

#Control measurments
ctrl <- trainControl(method = "cv", number = 10, savePredictions = TRUE, classProbs = TRUE)

seed <- 13
set.seed(seed)


metric <- "Accuracy"


Grid <- expand.grid(mtry= c(2,3,4))

#Model
rf_model <- train(default ~., data = train_cv, method = "rf", ntree=500, metric=metric, trlControl = ctrl, tuneGrid= Grid)

rf_model$bestTune
rf_model$finalModel
print(rf_model)
plot(rf_model, main="Random Forest Cross Validation")

```

#Test
```{r}
library(pROC)
library(ROCR)
#Class Predicitons 
predictions <- predict(rf_model, test_cv)
confusionMatrix(predictions, test_cv$default)

#Predict Probabilities
prob_predictions <- predict(rf_model, test_cv, type = "prob")

#ROC and AUC
auc <- auc(test_cv$default, prob_predictions[,2])

plot(roc(test_cv$default, prob_predictions[,2]))

#Plot 
perf <- prediction(prob_predictions[,2], test_cv$default)

auc <- performance(perf, "auc")

pred1 <- performance(perf, "tpr", "fpr")

plot(pred1, main = "ROC Random Forest", col = 2, lwd = 2)
abline(a=0, b=1, lwd=2, lty=2, col="gray")

```
